spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnet=true
    username: root
    password: admin
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: select 1

mybatis:
  type-aliases-package: com.niocoder.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.niocoder.common.mybatis.TkMapper
  identity: MYSQL

server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB